Adds VTKCells converter
JuliaVTK/ReadVTK.jl pull request #30
Opened 2023-04-16 19:37 UTC by Matthew-Whisenant

This PR follows up on the accidentally closed PR #28 

This PR sets up the workflow between ReadVTK -> WriteVTK by adding `to_meshcell`. Here the changes are:

- New function `to_meshcell` that converts `VTKCells` type to multiple WriteVTK compliant `MeshCells`
- Test in the first basic testing to check for `to_meshcell` correctness
- Added example of workflow in main index page. Let me know if you want something changed.
- Added my name to contributors. My university page got cleared in a address move but will be back up in a week or so. This new address will be the permanent one so no need for a recommit.
- Added .vscode to gitignore to help vscode users settings not mess with commits. Helps me not added whitespace to commits.

Note that I separated PRs in this to make more sense on an orthogonal feature level. My next PR will include more inclusive testing of ReadVTK -> WriteVTK workflow with ParaView and standard files. But this single test should at least cover testing of the conversion in and of itself.

2023-04-16 19:38 UTC, Matthew-Whisenant commented on docs/src/index.md
> +After modifications to the read VTK data, one can write back using WriteVTK.jl but must first convert cell objects using `to_meshcells`.
```suggestion
After modifications to the read VTK data, one can write back using [WriteVTK.jl](https://github.com/JuliaVTK/WriteVTK.jl) but must first convert cell objects using `to_meshcells`. 
```

2023-04-16 20:34 UTC, Matthew-Whisenant commented
I guess `range` was different for LTS Julia 1.6 so I updated so that it works. Strange that it worked on Julia 1 but failed on Julia 1.6. They must have reverted back because it didn't fail on 1.85. Regardless, I fixed so it works an all version. The fix was kinda weird and not really clear with the colon operator in-place of range but avoids a for loop.

2023-04-20 04:08 UTC, sloede requested changes
LGTM overall! I have only a few minor suggestions, but then this can be merged. Thanks for adding this very convenient feature!

2023-04-20 04:08 UTC, sloede commented on docs/src/index.md
> +* [Matthew Whisenant](https://volweb2.utk.edu/~mwhisena/)
You should also add your name to the list of authors in the main `README.md`

2023-04-20 15:14 UTC, Matthew-Whisenant commented on docs/src/index.md
> +* [Matthew Whisenant](https://volweb2.utk.edu/~mwhisena/)
Done. Forgot that the index and readme are different.

2023-04-20 15:19 UTC, Matthew-Whisenant commented
Does anyone have any suggestions on how to see what is causing the format check to fail? Or what the specifications are?

2023-04-20 15:26 UTC, sloede commented
> Does anyone have any suggestions on how to see what is causing the format check to fail? Or what the specifications are?

Sorry about that. This is a change that came into effect only this morning (Europe time). The easiest fix is to run JuliaFormatter on your branch as described in the [README.md](https://github.com/JuliaVTK/ReadVTK.jl#development).

2023-04-20 17:53 UTC, Matthew-Whisenant commented
> > Does anyone have any suggestions on how to see what is causing the format check to fail? Or what the specifications are?
> 
> Sorry about that. This is a change that came into effect only this morning (Europe time). The easiest fix is to run JuliaFormatter on your branch as described in the [README.md](https://github.com/JuliaVTK/ReadVTK.jl#development).

Yes I see that now. However it does not appear that the default settings works. Looking at the 'format-check' test, it appears to be flagging files I have not changed.

```
Formatting /home/runner/work/ReadVTK.jl/ReadVTK.jl/docs/make.jl
Formatting /home/runner/work/ReadVTK.jl/ReadVTK.jl/src/ReadVTK.jl
Formatting /home/runner/work/ReadVTK.jl/ReadVTK.jl/src/get_functions.jl
Formatting /home/runner/work/ReadVTK.jl/ReadVTK.jl/test/pvtk_files.jl
Formatting /home/runner/work/ReadVTK.jl/ReadVTK.jl/test/rectilinear.jl
Formatting /home/runner/work/ReadVTK.jl/ReadVTK.jl/test/runtests.jl
Formatting /home/runner/work/ReadVTK.jl/ReadVTK.jl/test/structuredgrid.jl
```

Is their a way to share your settings so that it always does yours?

2023-04-20 18:09 UTC, sloede approved these changes
LGTM!

2023-04-20 18:10 UTC, merged