Loose VTK XML version constaint
JuliaVTK/ReadVTK.jl pull request #44
Opened 2023-10-07 20:35 UTC by henry2004y

This PR attempts to loose the current constraint on the VTK XML version requirement, based on the discussion in #43.

2023-10-08 05:25 UTC, sloede requested changes
Thanks a lot for your contribution! With some minor changes, this LGTM.

2023-10-08 05:25 UTC, sloede commented on src/ReadVTK.jl
> +- `version`: currently only v1.0 and beyond are supported
```suggestion
- `version`: VTK XML file format version (v1.0 or later)
```
I think there is no useful spec information on this available publicly, so we can just be very neutral about this

2023-10-08 05:25 UTC, sloede commented on src/ReadVTK.jl
> +- `version`: currently only v1.0 and beyond are supported
```suggestion
- `version`: VTK XML file format version (v1.0 or later)
```
as above

2023-10-08 05:25 UTC, sloede commented on src/ReadVTK.jl
> +  @assert version ≥ v"1.0"
```suggestion
  @assert version >= v"1.0"
```
as above

2023-10-08 05:25 UTC, sloede commented on src/ReadVTK.jl
> +  @assert version ≥ v"1.0"
```suggestion
  @assert version >= v"1.0"
```
as above

2023-10-08 05:25 UTC, sloede commented on src/ReadVTK.jl
> +  @assert version ≥ v"1.0"
```suggestion
  @assert version >= v"1.0"
```
We prefer to only use ASCII characters for code

2023-10-08 12:55 UTC, henry2004y commented on src/ReadVTK.jl
> +- `version`: currently only v1.0 and beyond are supported
Yep

2023-10-08 13:40 UTC, sloede approved these changes

2023-10-08 13:51 UTC, merged

2023-10-09 07:07 UTC, sloede commented
v0.1.9 has just been released with your fix included.