Add support for field data
JuliaVTK/ReadVTK.jl pull request #66
Opened 2024-10-22 11:40 UTC by tverho

andresegido contributed a pull request to add support for field data (https://github.com/JuliaVTK/ReadVTK.jl/pull/42). However, due to the lack of a test, it was not merged. Here's a new pull request with a test included. Additionally, the `get_field_data` function is exported. I hope this can be now merged.

2024-10-25 12:10 UTC, ranocha requested changes
Thanks! I have two minor suggestions.

2024-10-25 12:10 UTC, ranocha commented on src/ReadVTK.jl
> +See also: [`VTKData`](@ref), [`get_point_data`](@ref), [`get_cell_data`](@ref)
Can you please add similar cross-references to other functions, e.g., reference `get_field_data` from the docstring of `get_point_data` etc.?

2024-10-25 12:10 UTC, ranocha commented on src/ReadVTK.jl
> +    @assert LightXML.name(xml_element) == "DataArray"
```suggestion
    LightXML.name(xml_element) != "DataArray" && continue
```

See https://github.com/JuliaVTK/ReadVTK.jl/pull/65

2024-10-25 12:24 UTC, tverho commented on src/ReadVTK.jl
> +See also: [`VTKData`](@ref), [`get_point_data`](@ref), [`get_cell_data`](@ref)
Done

2024-10-27 13:14 UTC, ranocha reviewed
Thanks a lot! Could you please add field data to

- https://github.com/JuliaVTK/ReadVTK.jl?tab=readme-ov-file#what-works
- https://github.com/JuliaVTK/ReadVTK.jl/blob/main/docs/src/index.md#what-works

and run the formatter locally to fix the CI run

https://github.com/JuliaVTK/ReadVTK.jl/actions/runs/11518148027/job/32122006751?pr=66

so that all required CI checks pass?

2024-10-29 09:05 UTC, ranocha approved these changes
Thanks a lot!

2024-10-29 10:59 UTC, ranocha commented on test/fielddata.jl
> +]
```suggestion
cells = [
  MeshCell(VTKCellTypes.VTK_TRIANGLE, [1, 4, 2]),
  MeshCell(VTKCellTypes.VTK_QUAD, [2, 4, 3, 5]),
]
```

2024-10-29 11:17 UTC, merged